# Generated by Django 5.2.8 on 2025-12-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size_file',
            field=models.BigIntegerField(null=True),
        ),
    ]
