# Generated by Django 5.2.8 on 2025-12-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0004_alter_file_size_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
    ]
