# Generated by Django 5.2.8 on 2025-12-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0005_remove_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
