# Generated by Django 5.2.8 on 2025-12-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0006_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
    ]
