# Generated by Django 5.2.8 on 2026-02-15 11:06

import my_server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0008_fileuser_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuser',
            name='file',
            field=models.FileField(null=True, upload_to=my_server.models.user_directory_path),
        ),
    ]
