# Generated by Django 5.2.8 on 2026-02-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0009_alter_fileuser_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuser',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
