# Generated by Django 5.2.8 on 2026-02-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0010_fileuser_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuser',
            old_name='token',
            new_name='file_token',
        ),
    ]
