# Generated by Django 5.2.8 on 2026-03-01 20:01

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0011_rename_token_fileuser_file_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileuser',
            options={'ordering': [django.db.models.functions.comparison.Cast('uploaded_at', output_field=models.IntegerField())]},
        ),
    ]
