# Generated by Django 5.2.8 on 2026-03-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0012_alter_fileuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileuser',
            options={},
        ),
    ]
