# Generated by Django 5.2.8 on 2026-03-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0013_alter_fileuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuser',
            name='last_download',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
