# Generated by Django 5.2.8 on 2026-03-07 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0015_alter_fileuser_last_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuser',
            name='last_download',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
