# Generated by Django 5.2.8 on 2026-03-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0020_alter_fileuser_last_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuser',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileuser',
            name='size_file',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
