# Generated by Django 5.2.8 on 2026-04-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_server', '0021_alter_fileuser_comments_alter_fileuser_size_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileuser',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
